version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    restart: always
    networks:
      - node-net
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    volumes: 
      - ./.data:/var/lib/mysql
    networks:
      - node-net
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3368:3306

  nginx:
    image: nginx:alpine
    restart: always
    working_dir: /usr/src/app
    environment:
      - DYNAMIC_FPM_HOST=app
    volumes:
      - ./node:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
    networks:
      - node-net
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  node-net:
    driver: bridge
